2 brokers and a load balancer
IOT-DSA/scala-broker pull request #52
Opened 2018-04-04 12:28 UTC by ilya-dubovskiy

2018-04-05 13:42 UTC, ilya-martynov commented
If you want to merge it you should add some reviewers.

2018-04-05 16:23 UTC, dmitriyisaev commented on docker/docker-compose/docker-compose.yaml
>  version: '2'
could we please create separate docker-compose for cluster solution. I mean we deffinetly should have 2 docker-compose files:
- for single mode
- for cluster mode.

Also would be better introduce flag in start shell script ro select mode.

2018-04-11 11:43 UTC, c9alex requested changes

2018-04-11 11:43 UTC, c9alex commented on docker/docker-compose/docker-compose-cluster.yaml
> +        - "80:5000"
Can you please change balancer port from '80' to '9080'?

2018-04-12 11:17 UTC, dmitriyisaev approved these changes
Looks fine

2018-04-20 09:31 UTC, closed without merging