it tests infrastructure
IOT-DSA/scala-broker pull request #54
Opened 2018-04-05 12:58 UTC by dmitriyisaev

Backlog item/140531

2018-04-09 14:06 UTC, c9alex requested changes

2018-04-09 14:06 UTC, c9alex commented on it/README.md
> +project it
Please add:
project root
docker:publishLocal

2018-04-09 14:10 UTC, dmitriyisaev commented on it/README.md
> +project it
Done, thanks

2018-04-10 14:18 UTC, c9alex approved these changes

2018-04-10 14:58 UTC, uralian approved these changes
Looks good to me

2018-04-12 11:14 UTC, merged