Feature/139920 wss support
IOT-DSA/scala-broker pull request #55
Opened 2018-04-13 13:21 UTC by vananyev

2018-04-13 13:23 UTC, dmitriyisaev requested changes
Please change target branch to dev

2018-04-13 13:28 UTC, dmitriyisaev reviewed
Do we have WSS test? I Mean that after https request for websocket connection we do connect vis wss?

2018-04-13 13:41 UTC, vananyev commented
@dmitriyisaev , right now the test does not contain wss connection. It will be in the next test. Could you check that this kind of test using is suitable?

2018-04-16 14:28 UTC, vananyev commented
@dmitriyisaev , i have changed the schema in the test, and debug it. Actually it uses the ssl security in the netty during data-exchange. So could you check does this test enough or we need more?

2018-04-17 09:22 UTC, dmitriyisaev approved these changes

2018-04-17 09:22 UTC, dmitriyisaev commented on conf/application.conf
> +	# Extra properties are: Alias: scala-broker, Password: acuitybrands
Thanks, very helpful.

2018-04-17 09:23 UTC, dmitriyisaev commented
Looks fine for me

2018-04-17 11:47 UTC, merged